// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.zcu.fav.kiv.pia.slezacek.model;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserVehicleRights_Roo_Configurable {
    
    declare @type: UserVehicleRights: @Configurable;
    
}
